name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: typst-community/setup-typst@v3
      - uses: fontist/setup-fontist@v2
      - run: fontist install "Times New Roman" -a
      - run: typst compile masodik.typ masodik.pdf --font-path ~/.fontist/fonts
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            masodik.pdf
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Release
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Masszív ápdét"
          files: |
            masodik.pdf